- name: Generate index.json
  run: |
    cd blog/posts
    echo "[" > index.json
    first=1
    for f in *.html; do
      # Extract date (first 10 chars) if filename starts with YYYY-MM-DD
      DATE=$(echo "$f" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}')
      if [ -n "$DATE" ]; then
        [ $first -ne 1 ] && echo "," >> index.json
        first=0
        echo "  { \"file\": \"$f\", \"date\": \"$DATE\" }" >> index.json
      fi
    done
    echo "" >> index.json
    echo "]" >> index.json
