name: Auto-Update Blog Post Index

on:
  push:
    paths:
      - 'blog/posts/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate index.json
        run: |
          cd blog/posts
          echo "[" > index.json
          find . -type f -name '*.html' | sort | sed 's|^\./||' | sed 's|^|  "|;s|$|",|' >> index.json
          sed -i '$ s/,$//' index.json
          echo "]" >> index.json

      - name: Commit index.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add blog/posts/index.json
          git commit -m "Update post index" || echo "No changes"
      
          # Pull remote changes to avoid push rejection
          git pull --rebase
      
          git push
