name: Auto-Update Blog Post Index

on:
  push:
    paths:
      - 'blog/posts/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate index.json
        run: |
          cd blog/posts
          shopt -s nullglob
          entries=()
          for f in *.html; do
            DATE=$(echo "$f" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}')
            if [ -n "$DATE" ]; then
              entries+=("{ \"file\": \"$f\", \"date\": \"$DATE\" }")
            fi
          done

          echo "[" > index.json
          if [ ${#entries[@]} -gt 0 ]; then
            (IFS=,; echo "  ${entries[*]}") >> index.json
          fi
          echo "]" >> index.json

          echo "index.json contents:"
          cat index.json

        continue-on-error: true

      - name: Commit index.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add blog/posts/index.json
          git commit -m "Update post index" || echo "No changes"
          git pull --rebase
          git push
